//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLauncherCmdPal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLauncherCmdPal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory for custom shortcuts.
        /// </summary>
        internal static string custom_shortcuts_desc {
            get {
                return ResourceManager.GetString("custom_shortcuts_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom shortcuts.
        /// </summary>
        internal static string custom_shortcuts_label {
            get {
                return ResourceManager.GetString("custom_shortcuts_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include games from Epic games.
        /// </summary>
        internal static string toggle_epic_desc {
            get {
                return ResourceManager.GetString("toggle_epic_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic Games.
        /// </summary>
        internal static string toggle_epic_label {
            get {
                return ResourceManager.GetString("toggle_epic_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle hidden games visibility.
        /// </summary>
        internal static string toggle_hidden_desc {
            get {
                return ResourceManager.GetString("toggle_hidden_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden games.
        /// </summary>
        internal static string toggle_hidden_label {
            get {
                return ResourceManager.GetString("toggle_hidden_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include games from Steam games.
        /// </summary>
        internal static string toggle_steam_desc {
            get {
                return ResourceManager.GetString("toggle_steam_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steam Games.
        /// </summary>
        internal static string toggle_steam_label {
            get {
                return ResourceManager.GetString("toggle_steam_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include games from Xbox games.
        /// </summary>
        internal static string toggle_xbox_desc {
            get {
                return ResourceManager.GetString("toggle_xbox_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Games.
        /// </summary>
        internal static string toggle_xbox_label {
            get {
                return ResourceManager.GetString("toggle_xbox_label", resourceCulture);
            }
        }
    }
}
